version: "3.1"
services:

    api_redis:
      image: redis:alpine
      container_name: api_redis
      restart: unless-stopped
      tty: true
      ports:
        - "6379:6379"
      networks:
        - api

    api_mariadb:
      image: mariadb:10.4
      container_name: api_mariadb
      restart: unless-stopped
      tty: true
      volumes:
        - database:/var/lib/mysql/
      environment:
        - MYSQL_ROOT_PASSWORD=root-pass
        - MYSQL_DATABASE=api
        - MYSQL_USER=user
        - MYSQL_PASSWORD=pass
      ports:
        - "8083:3306"
      networks:
        - api

    api_webserver:
      image: nginx:alpine
      container_name: api_webserver
      restart: unless-stopped
      tty: true
      working_dir: /application
      volumes:
        - ./src:/application
        - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
        - "8080:80"
      links:
        - api_mariadb
        - api_redis
      networks:
        - api

    api_php:
      build: .
      container_name: api_php
      restart: unless-stopped
      tty: true
      working_dir: /application
      volumes:
        - ./src:/application
      networks:
        - api

networks:
  api:
    driver: bridge

volumes:
  database:
    driver: local